version: '3.8'

services:
  ares-anticheat:
    image: mongo:7.0
    container_name: ares-anticheat
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ares_anticheat_data:/data/db

volumes:
  ares_anticheat_data:
